name: Build and deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

variables:
  AZURE_WEBAPP_NAME: 'nama-app-azure-anda' # Ganti dengan nama App Service Anda di Azure

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (npm)
        run: |
          cd Dev/ProjectManagement.App
          npm install

      - name: Restore dependencies (dotnet)
        run: dotnet restore Dev/ProjectManagement.App/ProjectManagement.App.csproj

      - name: Build with dotnet
        run: dotnet build Dev/ProjectManagement.App/ProjectManagement.App.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish Dev/ProjectManagement.App/ProjectManagement.App.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef

      - name: Create Migration Bundle
        run: |
          dotnet ef migrations bundle --project Dev/ProjectManagement.App/ProjectManagement.App.csproj -o ${{env.DOTNET_ROOT}}/myapp/migrate --self-contained

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Run Migrations
        run: |
          chmod +x ./migrate
          ./migrate --connection "${{ secrets.AZURE_SQL_CONNECTION_STRING }}"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
